backend/backend/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    # not logged in
    path('', views.index, name="index"),
    path('search/', views.search, name="search"),

    # logged in
    path('home/', views.home, name="home"),
    path('post/', views.addWord, name="post"),
    path('results/', views.results, name="results"),
    path('dashboard/', views.dashbBoard, name="dashboard"),

    # authentication
    path('signup/', views.signup, name="signup"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),

]

backend/main/models.py
from django.db import models

# Create your models here.
class Word(models.Model):
    word = models.CharField(max_length=255, unique=True)
    pos = models.CharField(max_length=255)
    description = models.TextField()
    inSentence = models.TextField()

    def __str__(self):
        return self.word

backend/main/forms.py
from calendar import c
from dataclasses import fields
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import Word

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class AddWordForm(ModelForm):
    class Meta:
        model = Word
        fields = '__all__'

backend/main/views.py
# default imports
from multiprocessing import context
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib import messages

from django.contrib.auth.decorators import login_required

# my Imports
from .models import Word
from .forms import CreateUserForm, AddWordForm

# Not logged In
def index(request):
    if request.user.is_authenticated:
        return redirect('main:home')
    else:
        word = Word.objects.order_by('word')
        context = {
            'word': word
        }
        return render(request, 'main/index.html', context)

def search(request):
    if request.user.is_authenticated:
        return redirect('main:home')
    else:
        if request.method == "POST": 
            searched = request.POST['searched']
            word = Word.objects.filter(word__contains=searched)
            context = {
                'searched': searched,
                'words': word
            }
            return render(request, 'main/search.html', context)
        else:
            return render(request, 'main/search.html')

# Authentication
def signup(request):
    if request.user.is_authenticated:
        return redirect('main:home')
    else:
        form = CreateUserForm()

        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()

                user = form.cleaned_data.get('username')
                messages.success(request, 'Account Has Been Created For ' + user +' . Now You Can Log In')

                return redirect('main:login')


    context = {
        'form': form
    }
    return render(request, 'main/auth/signup.html', context)

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('main:home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('main:home')


        return render(request, 'main/auth/login.html')

def logoutUser(request):
    logout(request)
    return redirect('main:index')


# If user is logged in
@login_required(login_url='main:index')
def home(request):
    word = Word.objects.order_by('word')
    context = {
        'word': word
    }
    return render(request, 'main/dashboard/home.html', context)

@login_required(login_url='main:index')
def results(request):
    if request.method == "POST": 
        searched = request.POST['searched']
        word = Word.objects.filter(word__contains=searched)
        context = {
            'searched': searched,
            'words': word
        }
        return render(request, 'main/dashboard/search.html', context)
    else:
        return render(request, 'main/dashboard/search.html')

@login_required(login_url='main:index')
def dashbBoard(request):
    return render(request, 'main/dashboard/dashboard.html')

@login_required(login_url='main:index')
def addWord(request):
    form = AddWordForm

    if request.method == 'POST':
        form = AddWordForm(request.POST)
        if form.is_valid():
            form.save()

            word = form.cleaned_data.get('word')
            messages.success(request, 'You added ' + word)

            return redirect('main:post')

    context = {
        'form': form
    }
    return render(request, 'main/dashboard/post.html', context)

backend/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Ndamvetsa {% block title %} {% endblock %}</title>
</head>
<body class="bg-gray-100 flex flex-col justify-center items-center w-full">
        <!-- Nav bar -->
        <nav class="flex justify-between items-center bg-gray-50 shadow-md w-full px-8 py-4">
            <h1 class="text-blue-400 text-3xl hover:text-blue-500"><a href="{% url 'main:index' %}">Ndamvetsa</a></h1>
            <h2 class="underline text-xl "><a href="{% url 'main:signup'%}">Signup</a></h2>
        </nav>
    
        <!-- Search bar -->
        <section class="my-10 w-10/12">
            <form action="{% url 'main:search' %}" method="post">
                {% csrf_token %}
                <input class="w-full px-6 py-4 rounded bg-blue-100" type="search" name="searched" placeholder="search">
            </form>
        </section>
    {% block content %}
    {% endblock %}
</body>
</html>

backend/templates/content.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Ndamvetsa {% block title %} {% endblock %}</title>
</head>
<body class="bg-gray-100 flex flex-col justify-center items-center w-full">
        <!-- Nav bar -->
        <nav class="flex justify-between items-center bg-gray-50 shadow-md w-full px-8 py-4">
            <div class="flex space-x-4 items-center">
                <h1 class="text-blue-400 text-3xl hover:text-blue-500"><a href="{% url 'main:home' %}">Ndamvetsa</a></h1>
                <p class="text-2xl capitalize"><a href="{% url 'main:dashboard' %}">dashboard</a></p>
            </div>
            <div class="flex space-x-4 justify-center items-center">
                <span class="text-xl capitalize"n>Hello, {{request.user}}</span>
                <h2 class="underline text-xl"><a href="{% url 'main:logout' %}">Logout</a></h2>
            </div> 
        </nav>
    
    {% block content %}
    {% endblock %}
</body>
</html>

backend/templates/main/dashboard/dashboard.html
{% extends 'content.html' %}

{% block content %}
    <main class="flex flex-col w-11/12 justify-center items-center">
        <section class="grid grid-cols-3 gap-8 justify-center items-center justify-items-center my-10 w-11/12">
            <div class="flex flex-col bg-gray-50 rounded shadow-md w-full h-52 ">
                <p class="text-xl text-center py-4 shadow w-full">Words Added</p>
                <div class="flex justify-center items-center h-full">
                    <p class="text-xl">50</p>
                </div>
            </div>
            <div class="flex flex-col bg-gray-50 rounded shadow-md w-full h-52 ">
                <a href="{% url 'main:post' %}" class="flex justify-center items-center h-full">
                    <p class="text-xl">ADD WORD</p>
                </a>
            </div>
            <div class="flex flex-col bg-gray-50 rounded shadow-md w-full h-52 ">
                <p class="text-xl text-center py-4 shadow w-full">Approve Pending</p>
                <div class="flex justify-center items-center h-full">
                    <p class="text-xl">50</p>
                </div>
            </div>
        </section>

        <section class="flex flex-col justify-center items-center my-10 w-full ">
            <h1 class="text-xl text-left py-2 w-full border-b border-gray-500">User Profile Page</h1>

            <div>

            </div>
        </section>
    </main>
{% endblock %}

backend/templates/main/dashboard/home.html
{% extends 'content.html' %}    

{% block content %}
    <!-- dictionary -->
    <main class="w-10/12">
        <section>
            {% for word in word %}
            <div class="border-b border-gray-400 py-6">
                <h1 class="text-xl font-bold">{{ word.word }}</h1>
                <div class="px-6">
                    <span class="italic font-light py-2">{{ word.pos }}</span>
                    <p>{{ word.description }}</p>
                    <p class="">"{{ word.inSentence }}"</p>
                </div>
            </div>
            {% endfor %}
        </section>
    </main>
{% endblock %}

backend/templates/main/dashboard/post.html
{% extends 'content.html' %}


{% block content %}    
    <!-- Form -->
    <main class="flex flex-col items-center justify-center w-10/12">
        <section class="flex flex-col justify-center items-center w-full shadow-xl mt-10 bg-white px-8 pt-10 rounded-lg">
            <h1 class="text-2xl">Add Word</h1>

            {% for message in messages %}
            <p class="text-green-600 py-4 bg-green-100 w-11/12 rounded shadow text-center mt-4">{{message}}</p>
            {% endfor %}

            <!-- Form -->
            <form action="" class="flex flex-col justify-center items-center py-10 space-y-6 w-11/12" method="post">
                {% csrf_token %}

                {{ form.word }}

                {{ form.pos }}

                {{ form.description }}

                {{ form.inSentence }}

                <button class="bg-blue-400 text-white py-4 rounded cursor-pointer hover:bg-transparent hover:border hover:border-blue-400 hover:text-black w-full" type="submit">Post</button>
            </form>
            <!-- end of form -->

        </section>
        
    </main>

    <script>
        var form_fields = document.getElementsByTagName('input')
        let text_fields = document.getElementsByTagName('textarea')

        form_fields[1].placeholder='Enter Word';
        form_fields[2].placeholder='Part of speech';

        text_fields[0].placeholder='Enter Description (In English)';
        text_fields[1].placeholder='Use word in Sentence';
        

        for (var field in form_fields){	
			form_fields[field].className += 'w-full px-6 py-4 rounded border-2 border-blue-400 outline-none'
		}

        for (var field in text_fields){	
			text_fields[field].className += 'w-full px-6 py-4 rounded border-2 border-blue-400 outline-none'
		}
    </script>

{% endblock%}

backend/templates/main/dashboard/search.html
{% extends 'content.html' %}


<!-- {% block title %} | Search results {% endblock %}  -->

{% block content %}
    <!-- Search bar -->
    <section class="my-10 w-10/12">
        <form action="{% url 'main:results' %}" method="post">
            {% csrf_token %}
            <input class="w-full px-6 py-4 rounded bg-blue-100" type="search" name="searched" placeholder="search">
        </form>
    </section>

    <!-- Body ody -->
    <main class="w-10/12">
        {% if searched %}
        <section>
            {% for word in words %}
            <div class="border-b border-gray-400 py-6">
                <h1 class="text-xl font-bold">{{ word.word }}</h1>
                <div class="px-6">
                    <span class="italic font-light py-2">{{ word.pos }}</span>
                    <p>{{ word.description }}</p>
                    <p class="">"{{ word.inSentence }}"</p>
                </div>
            </div>
            {% endfor %}
        </section>
        {% else %}
            <div class="flex justify-center items-center w-full">
                <p class="mt-10 text-2xl">You forgot to search for a word</p>
            </div>
        {%endif%}
    </main>
{% endblock %}

backend/templates/main/index.html
{% extends 'base.html' %}    

{% block content %}
    <!-- dictionary -->
    <main class="w-10/12">
        <section>
            {% for word in word %}
            <div class="border-b border-gray-400 py-6">
                <h1 class="text-xl font-bold">{{ word.word }}</h1>
                <div class="px-6">
                    <span class="italic font-light py-2">{{ word.pos }}</span>
                    <p>{{ word.description }}</p>
                    <p class="">"{{ word.inSentence }}"</p>
                </div>
            </div>
            {% endfor %}
        </section>
    </main>
{% endblock %}

backend/templates/main/search.html
{% extends 'base.html' %}


{% block title %} | Search results {% endblock %} 

{% block content %}
    <!-- Body ody -->
    <main class="w-10/12">
        {% if searched %}
        <section>
            {% for word in words %}
            <div class="border-b border-gray-400 py-6">
                <h1 class="text-xl font-bold">{{ word.word }}</h1>
                <div class="px-6">
                    <span class="italic font-light py-2">{{ word.pos }}</span>
                    <p>{{ word.description }}</p>
                    <p class="">"{{ word.inSentence }}"</p>
                </div>
            </div>
            {% endfor %}
        </section>
        {% else %}
            <div class="flex justify-center items-center w-full">
                <p class="mt-10 text-2xl">You forgot to search for a word</p>
            </div>
        {%endif%}
    </main>
{% endblock %}

backend/templates/main/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Ndamvetsa | Sign Up</title>
</head>
<body class="bg-gray-100 flex flex-col justify-center items-center w-full">
    <nav class="flex justify-center items-center bg-gray-50 shadow-md w-full px-8 py-4">
        <h1 class="text-blue-400 text-3xl hover:text-blue-500"><a href="{% url 'main:index' %}">Ndamvetsa</a></h1>
    </nav>

    <main class="flex flex-col justify-center items-center w-10/12 ">
        <section class="flex flex-col justify-center items-center w-full shadow-xl mt-10 bg-white px-8 rounded-lg">
            <h1 class="pt-10 text-2xl">Sign Up</h1>
            <form  class="flex flex-col justify-center items-center py-10 space-y-6 w-11/12" action="" method="post">
                {% csrf_token %}


                {{ form.username }}

                {{ form.email }}

                {{ form.password1 }}

                {{ form.password2 }}

                <p class="w-full">Already a member?  <a href="{% url 'main:login' %}" class="font-bold hover:text-blue-400">Log in</a></p>
                <button class="bg-blue-400 text-white py-4 rounded cursor-pointer hover:bg-transparent hover:border hover:border-blue-400 hover:text-black w-full" type="submit" name="signup">Signup</button>
            </form>
        </section> 
    </main>

    <script>
        var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Your Username';
		form_fields[2].placeholder='Your Email';
		form_fields[3].placeholder='Enter your password';
		form_fields[4].placeholder='Verify your Password';

        for (var field in form_fields){	
			form_fields[field].className += 'w-full px-6 py-4 rounded border-2 border-blue-400 outline-none'
		}
    </script>
</body>
</html>